# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.core.grpc_gen.whisper_rknn.v1 import worker_pb2 as whisper__rknn_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in whisper_rknn/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encode = channel.unary_unary(
                '/whisper_rknn.v1.EncodeService/Encode',
                request_serializer=whisper__rknn_dot_v1_dot_worker__pb2.EncodeRequest.SerializeToString,
                response_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.EncodeThenDecode = channel.unary_unary(
                '/whisper_rknn.v1.EncodeService/EncodeThenDecode',
                request_serializer=whisper__rknn_dot_v1_dot_worker__pb2.EncodeThenDecodeRequest.SerializeToString,
                response_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.DecodeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/whisper_rknn.v1.EncodeService/Health',
                request_serializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class EncodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Encode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeThenDecode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encode': grpc.unary_unary_rpc_method_handler(
                    servicer.Encode,
                    request_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.EncodeRequest.FromString,
                    response_serializer=whisper__rknn_dot_v1_dot_worker__pb2.EncodeResponse.SerializeToString,
            ),
            'EncodeThenDecode': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeThenDecode,
                    request_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.EncodeThenDecodeRequest.FromString,
                    response_serializer=whisper__rknn_dot_v1_dot_worker__pb2.DecodeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthRequest.FromString,
                    response_serializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whisper_rknn.v1.EncodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('whisper_rknn.v1.EncodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Encode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper_rknn.v1.EncodeService/Encode',
            whisper__rknn_dot_v1_dot_worker__pb2.EncodeRequest.SerializeToString,
            whisper__rknn_dot_v1_dot_worker__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeThenDecode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper_rknn.v1.EncodeService/EncodeThenDecode',
            whisper__rknn_dot_v1_dot_worker__pb2.EncodeThenDecodeRequest.SerializeToString,
            whisper__rknn_dot_v1_dot_worker__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper_rknn.v1.EncodeService/Health',
            whisper__rknn_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
            whisper__rknn_dot_v1_dot_worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decode = channel.unary_unary(
                '/whisper_rknn.v1.DecodeService/Decode',
                request_serializer=whisper__rknn_dot_v1_dot_worker__pb2.DecodeRequest.SerializeToString,
                response_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.DecodeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/whisper_rknn.v1.DecodeService/Health',
                request_serializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class DecodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Decode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decode': grpc.unary_unary_rpc_method_handler(
                    servicer.Decode,
                    request_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.DecodeRequest.FromString,
                    response_serializer=whisper__rknn_dot_v1_dot_worker__pb2.DecodeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthRequest.FromString,
                    response_serializer=whisper__rknn_dot_v1_dot_worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whisper_rknn.v1.DecodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('whisper_rknn.v1.DecodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper_rknn.v1.DecodeService/Decode',
            whisper__rknn_dot_v1_dot_worker__pb2.DecodeRequest.SerializeToString,
            whisper__rknn_dot_v1_dot_worker__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper_rknn.v1.DecodeService/Health',
            whisper__rknn_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
            whisper__rknn_dot_v1_dot_worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
